AWSTemplateFormatVersion: '2010-09-09'
Description: Hosted zone (after getting domain name), ACM cert, OAI, S3 static site (StaticResourcesBucket) and policy, Cloudfront distribution, hosted zone record sets

Parameters:
   # TODO: UPDATE Default WITH DESIRED DOMAIN NAME
   DomainName:
      Type: String
      Default: sarasotaremodeling.com

   # TODO: UPDATE Default WITH MANUALLY CREATED HOSTED ZONE ID FROM Route53
   HostedZoneId:
      Type: String
      Default: Z02784902NA8LITBBLEBM

Resources:
   # NOTE: THIS RESOURCE IS NOT NEEDED! HOSTED ZONE ALREADY CREATED MANUALLY
   # HostedZone:
   #   Type: AWS::Route53::HostedZone
   #   Properties:
   #     Name: !Ref DomainName

   Certificate:
      # TODO: REMEMBER TO MANUALLY VALIDATE ACM CONSOLE
      Type: AWS::CertificateManager::Certificate
      Properties:
         DomainName: !Ref DomainName
         SubjectAlternativeNames:
            - !Ref DomainName
            - !Sub www.${DomainName}
         DomainValidationOptions:
            - DomainName: !Ref DomainName
              HostedZoneId: !Ref HostedZoneId
            - DomainName: !Sub www.${DomainName}
              HostedZoneId: !Ref HostedZoneId
         ValidationMethod: DNS

   OriginAccessIdentity:
      Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
      Properties:
         CloudFrontOriginAccessIdentityConfig:
            Comment: !Sub ${AWS::StackName}-s3-origin-oai

   StaticResourcesBucket:
      Type: AWS::S3::Bucket
      Properties:
         BucketName: !Ref DomainName
         BucketEncryption:
            ServerSideEncryptionConfiguration:
               - ServerSideEncryptionByDefault:
                    SSEAlgorithm: AES256
         PublicAccessBlockConfiguration:
            BlockPublicAcls: true
            BlockPublicPolicy: true
            IgnorePublicAcls: true
            RestrictPublicBuckets: true

   StaticResourcesBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
         Bucket: !Ref StaticResourcesBucket
         PolicyDocument:
            Statement:
               - Effect: Allow
                 Principal:
                    AWS: !Sub arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${OriginAccessIdentity}
                 Action: s3:GetObject
                 Resource: !Sub arn:aws:s3:::${StaticResourcesBucket}/*

   Distribution:
      Type: AWS::CloudFront::Distribution
      Properties:
         DistributionConfig:
            Aliases:
               - !Ref DomainName
               - !Sub www.${DomainName}
            Origins:
               - DomainName: !Sub ${StaticResourcesBucket}.s3.${AWS::Region}.amazonaws.com
                 Id: S3Origin
                 S3OriginConfig:
                    OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${OriginAccessIdentity}
            Enabled: true
            DefaultRootObject: index.html
            DefaultCacheBehavior:
               AllowedMethods:
                  - DELETE
                  - GET
                  - HEAD
                  - OPTIONS
                  - PATCH
                  - POST
                  - PUT
               TargetOriginId: S3Origin
               ViewerProtocolPolicy: redirect-to-https
               CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
            PriceClass: PriceClass_100
            ViewerCertificate:
               AcmCertificateArn: !Ref Certificate
               SslSupportMethod: sni-only

   HostedZoneRecordSetGroup:
      Type: AWS::Route53::RecordSetGroup
      Properties:
         HostedZoneId: !Ref HostedZoneId
         RecordSets:
            - Name: !Ref DomainName
              Type: A
              AliasTarget:
                 # NOTE: SINCE USING CLOUDFRONT, DO NOT CHANGE HostedZoneID
                 HostedZoneId: Z2FDTNDATAQYW2
                 DNSName: !GetAtt
                    - Distribution
                    - DomainName
            - Name: !Sub www.${DomainName}
              Type: A
              AliasTarget:
                 # NOTE: SINCE USING CLOUDFRONT, DO NOT CHANGE HostedZoneID
                 HostedZoneId: Z2FDTNDATAQYW2
                 DNSName: !GetAtt
                    - Distribution
                    - DomainName
            - Name: !Ref DomainName
              Type: AAAA
              AliasTarget:
                 # NOTE: SINCE USING CLOUDFRONT, DO NOT CHANGE HostedZoneID
                 HostedZoneId: Z2FDTNDATAQYW2
                 DNSName: !GetAtt
                    - Distribution
                    - DomainName
            - Name: !Sub www.${DomainName}
              Type: AAAA
              AliasTarget:
                 # NOTE: SINCE USING CLOUDFRONT, DO NOT CHANGE HostedZoneID
                 HostedZoneId: Z2FDTNDATAQYW2
                 DNSName: !GetAtt
                    - Distribution
                    - DomainName
