name: CI

on:
   push:
      branches:
         - master

jobs:
   build:
      runs-on: ubuntu-latest
      env:
         BUCKET_NAME: sarasotaremodeling.com

      name: build and deploy files
      steps:
         - uses: actions/checkout@v2
           with:
              fetch-depth: 0
         - uses: actions/setup-node@v2
           with:
              node-version: 18
         - run: npm ci

         # configure the gibhub runner w/ aws cli to get the aws access key and secret key in github settings
         - name: configure AWS CLI on runner
           uses: aws-actions/configure-aws-credentials@v1
           with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: us-east-1

         - name: build website files
           run: npm run build

         - name: deploy website files
           run: |
              aws s3 rm s3://${{ env.BUCKET_NAME }} --recursive
              aws s3 cp dist s3://${{ env.BUCKET_NAME }} --recursive
              aws s3 rm s3://${{ env.BUCKET_NAME }}/.github/workflows/main.yaml
              aws cloudfront create-invalidation --distribution-id E1GAI381JAJQJU --paths "/*"
